### ISSUE TITLE
Dark theme not applied by plugins and some other quick errors

### ISSUE THREAD

**Issue by PowerChaos** [Brugman/cyberpanel-dark-theme-plus#1]
Thank you for the dark theme
there is a small bug ( probably cyberpanel related )  that does not apply the custom css to the plugin page or filemanager

1. /configservercsf/ and /filemanager/ shows the default theme ,so there need to be a way to inject the custom theme into the original theme so it get forced on all pages or a "css swapper"

1. /users/listUsers shows notihng as white name on a white table result in a white page .. kinda hard to read on a white background
2. /packages/listPackages same as above , white table ..
3. /dataBases/createDatabase shows a white select box with white text 
4. /dns/addDeleteDNSRecords , white table
5. /ftp/createFTPAccount, white select

thats it for now , as almost every link contains something related to table or select , so after a fix i can test the other stuff a bit more
the first errors are related that it just does not parse the custom css, so probably not a fix in here

Thank you
Greetings from PowerChaos

**Comment by Brugman** [comment]
Thanks for the paths. I only styled the most superficial pages so far. Going back in tonight.
